spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/california
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  config:
    import: classpath:/application-jwt.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace